### ISSUE TITLE
Fix test_traceroute

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm-iosxr#11]
It's currently broken:

```
The command "nosetests -v TestIOSXRDriver:TestGetterIOSXRDriver.test_get_probes_results" exited with 0.
0.16s$ nosetests -v TestIOSXRDriver:TestGetterIOSXRDriver.test_traceroute
test_traceroute (TestIOSXRDriver.TestGetterIOSXRDriver) ... ERROR
======================================================================
ERROR: test_traceroute (TestIOSXRDriver.TestGetterIOSXRDriver)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/napalm_base-0.12.0-py2.7.egg/napalm_base/test/base.py", line 392, in test_traceroute
    result = result and self._test_model(models.traceroute, probe_result)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/napalm_base-0.12.0-py2.7.egg/napalm_base/test/base.py", line 147, in _test_model
    same_class = isinstance(data[key], instance_class)
KeyError: 'rtt'
-------------------- >> begin captured stdout << ---------------------
model_keys: ['host_name', 'ip_address', 'rtt']
data_keys: ['host_name', 'ip_address']
--------------------- >> end captured stdout << ----------------------
----------------------------------------------------------------------
Ran 1 test in 0.003s
FAILED (errors=1)
```

**Comment by mirceaulinic** [comment]
Perfect! I will do my best to fix it asap, but can't promise this will
happen earlier than next Tuesday. But I'll try. Thanks!

Le sam. 30 avr. 2016 19:49, David Barroso notifications@github.com a
écrit :

**Comment by dbarrosop** [comment]
I tried to fix it using your mocked data but the XML that IOSXR returns is pure garbage so I am not sure if I fixed the issue or just replaced a bug we can detect for a bug we can't.

napalm-automation/napalm-iosxr/pull/12
